# Generated by relwirec from i2c_ns.rw. Load with host/relwire_tt.py.
WORDS = [0x01a2000, 0x0182000, 0x0900804, 0x02a4000, 0x0194000, 0x03a4000, 0x0182000, 0x12a0400, 0x0194000, 0x13a0400, 0x0182000, 0x0900804, 0x02a4480, 0x0194000, 0x03a4480, 0x0182000, 0x12a0880, 0x0194000, 0x13a0880, 0x0182000, 0x02a0900, 0x0194000, 0x03a8900, 0x01b2000, 0x0000000]
CONSTS = [65535, 1, 2, 0, 0, 0, 0, 0]
WIRES = [("SCL", 1), ("SDA", 1)]  # (name, 0 push-pull / 1 dominant-low / 2 dominant-high)
LAYOUT = {"addr": (0, 8), "ack": (8, 1), "data": (9, 8), "ack2": (17, 1), "stop_lo": (18, 1)}  # field: (first data-memory bit, width)
LITS = {"stop_lo": 0}
ROLES = {"controller": 0, "target": 1}
TICK_CYCLES = 11
